// Generated by shadcn/ui
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

import LEAFLET from '@/consts/LEAFLET';
import L from 'leaflet';

function converMapCoordsToWorldCoords(x: number, y: number): { x: number; z: number } {
	return {
		x: Math.floor(x * LEAFLET.TILE_SIZE),
		z: Math.floor(-y * LEAFLET.TILE_SIZE),
	};
};

function convertWorldCoordsToMapCoords(x: number, z: number): L.Point {
	return L.point(
		x / LEAFLET.TILE_SIZE,
		-z / LEAFLET.TILE_SIZE,
	);
}

export const Coords = {
	mapToWorld: converMapCoordsToWorldCoords,
	worldToMap: convertWorldCoordsToMapCoords,
};