// Generated by shadcn/ui
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

import LEAFLET from '@/consts/LEAFLET';
import L from 'leaflet';

function convertMapCoordsToWorldCoords(x: number, y: number): { x: number; z: number } {
	return {
		// Map coord system: Latitude increases upwards, Longitude increases rightwards
		// World coord system: X increases rightwards, Z increases downwards
		// Therefore, world Z = -map Y
		x: Math.floor(x * LEAFLET.TILE_SIZE),
		z: -Math.floor(y * LEAFLET.TILE_SIZE),
	};
};

function convertWorldCoordsToMapCoords(x: number, z: number): L.LatLng {
	return L.latLng(
		-z / LEAFLET.TILE_SIZE, 
		x / LEAFLET.TILE_SIZE
	);
}

function tileCoordsToChunkCoords(tile: L.Coords): { x: number; z: number } {
	return {
		x: Math.floor(tile.x),
		z: Math.floor(tile.y),
	};
}

function chunkCoordsToTilePoint(chunkX: number, chunkZ: number): L.Point {
	// Reverse of above: tile Y = -chunkZ
	return L.point(chunkX, chunkZ);
}

export const Coords = {
	mapToWorld: convertMapCoordsToWorldCoords,
	worldToMap: convertWorldCoordsToMapCoords,
	tileToChunk: tileCoordsToChunkCoords,
	chunkToTile: chunkCoordsToTilePoint,
};